# Generated by Django 4.1 on 2022-08-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegoSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('product_id', models.CharField(max_length=50, unique=True)),
                ('theme', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('available', models.BooleanField(default=False)),
                ('age', models.CharField(max_length=3)),
                ('elements', models.IntegerField()),
                ('link', models.TextField()),
                ('minifigures', models.IntegerField(blank=True)),
            ],
        ),
    ]
