# Generated by Django 4.0.7 on 2022-08-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legoscraper', '0002_alter_legoset_minifigures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legoset',
            name='age',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='legoset',
            name='available',
            field=models.CharField(max_length=100),
        ),
    ]
