# Generated by Django 4.0.7 on 2022-08-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legoscraper', '0003_alter_legoset_age_alter_legoset_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legoset',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
