# Generated by Django 4.0.7 on 2022-08-22 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legoscraper', '0004_alter_legoset_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='legoset',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='legoset',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='legoset',
            name='age',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legoscraper.agecategory'),
        ),
        migrations.AlterField(
            model_name='legoset',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legoscraper.theme'),
        ),
    ]
