# Generated by Django 4.0.7 on 2022-08-26 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legoscraper', '0005_agecategory_theme_alter_legoset_available_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agecategory',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='legoset',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='theme',
            options={'ordering': ['name']},
        ),
    ]
