# Generated by Django 4.0.7 on 2022-08-26 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legoscraper', '0006_alter_agecategory_options_alter_legoset_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legoset',
            name='id',
        ),
        migrations.AlterField(
            model_name='legoset',
            name='product_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
