# Generated by Django 4.0.7 on 2022-08-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legoscraper', '0007_remove_legoset_id_alter_legoset_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agecategory',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
