# Generated by Django 4.0.7 on 2022-08-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legoscraper', '0009_legoset_img_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='legoset',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
